### ISSUE TITLE
Version 6.15 not working on Win Xp while Version 6.0 is working.

### ISSUE THREAD

**Issue by MaciFla** [RickStrahl/wwDotnetBridge#6]
I found version **6.15** not working on my Xp Professional Sp2 (or Sp3)  with .NET Framework v4.0.30319 ("Cannot load CLR Instance"), while version **6.00** is working fine.

**Comment by RickStrahl** [comment]
Switched to .NET 4. Make sure you're calling .NET 4.0 components or you have to explicitly specify V2 when loading wwdotnetbridge for the first time.

**Comment by MaciFla** [comment]
`
DO wwDotnetBridge
loBridge = CREATE("wwDotnetBridge","V4")
?loBridge.GetDotnetVersion()
`
result: .NET Version: 4.0.30319.1
The same procedure  works ok with version 6.00. For my need is enough version 6, and Thank You for that.

**Comment by RickStrahl** [comment]
Latest version is compiled with .NET 4.5 in order to support 4.5+ assembly loading. .NET 4.5 does not support Windows XP or Vista (or Server 2003 or 2008 original). For those older OSs you need to use the older version.

West Wind Client Tools and Web Connection both ship with the new and old dlls but this project requires that you build or download the appropriate packages. I believe 6.10 is where the cutoff was.
